package com.qrmenu.qrcode;

import com.qrmenu.common.ConflictException;
import com.qrmenu.common.InvalidUrlException;
import com.qrmenu.restaurant.Restaurant;
import com.qrmenu.restaurant.RestaurantOffer;
import com.qrmenu.restaurant.RestaurantService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.HashSet;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest
@ActiveProfiles("test")
class QrCodeServiceTest {

    @Autowired
    private QrCodeService qrCodeService;

    @Autowired
    private RestaurantService restaurantService;

    @Autowired
    private QrCodeRepository qrCodeRepository;

    @Test
    void createsQrCodeWithGeneratedOpaqueCode() {
        Restaurant restaurant = restaurantService.create("Snack Test", RestaurantOffer.BASIC);

        QrCode qrCode = qrCodeService.create(restaurant.getId(), "QR entrée", "https://example.com/menu.pdf");

        assertThat(qrCode.getId()).isNotNull();
        assertThat(qrCode.getCode()).isNotBlank();
        assertThat(qrCode.getCode()).hasSize(10); // longueur par défaut du générateur
        assertThat(qrCode.getCode()).isNotEqualTo("1"); // jamais un simple compteur
        assertThat(qrCode.isActive()).isTrue();
        assertThat(qrCode.getRestaurantId()).isEqualTo(restaurant.getId());
    }

    /**
     * Un restaurant n'a jamais qu'un seul QR (voir plus bas) : l'unicité des codes se
     * vérifie donc sur plusieurs restaurants, pas en créant plusieurs QR pour un seul.
     */
    @Test
    void generatesUniqueCodesAcrossManyRestaurants() {
        Set<String> codes = new HashSet<>();

        for (int i = 0; i < 50; i++) {
            Restaurant restaurant = restaurantService.create("Snack Unicité " + i, RestaurantOffer.BASIC);
            QrCode qrCode = qrCodeService.create(restaurant.getId(), "QR " + i, "https://example.com/menu-" + i);
            assertThat(codes.add(qrCode.getCode())).isTrue();
        }
    }

    @Test
    void rejectsDangerousDestinationUrl() {
        Restaurant restaurant = restaurantService.create("Snack Sécurité", RestaurantOffer.BASIC);

        assertThatThrownBy(() ->
                qrCodeService.create(restaurant.getId(), "QR", "javascript:alert(1)")
        ).isInstanceOf(InvalidUrlException.class);
    }

    // ------------------------------------------------------------ 1 restaurant = 1 QR

    /**
     * Chemin normal : jamais une action du restaurateur, toujours déclenché à la
     * création du restaurant ({@code RestaurantAdminController.create}).
     */
    @Test
    void ensureQrCodeCreatesTheOnlyQrWithAnAutoGeneratedDestination() {
        Restaurant restaurant = restaurantService.create("Snack Auto", RestaurantOffer.PRO);

        QrCode qrCode = qrCodeService.ensureQrCode(restaurant);

        assertThat(qrCode.getRestaurantId()).isEqualTo(restaurant.getId());
        assertThat(qrCode.getCode()).isNotBlank();
        assertThat(qrCode.isActive()).isTrue();
        // Destination auto-générée vers la page de menu de ce code — jamais saisie,
        // valide même avant qu'aucun menu n'existe (voir PublicMenuController).
        assertThat(qrCode.getDestinationUrl()).endsWith("/m/" + qrCode.getCode());
    }

    /** Idempotent : rappelable sans risque (restaurant déjà créé, backfill au démarrage). */
    @Test
    void ensureQrCodeIsIdempotent() {
        Restaurant restaurant = restaurantService.create("Snack Idempotent", RestaurantOffer.PRO);

        QrCode first = qrCodeService.ensureQrCode(restaurant);
        QrCode second = qrCodeService.ensureQrCode(restaurant);

        assertThat(second.getId()).isEqualTo(first.getId());
        assertThat(second.getCode()).isEqualTo(first.getCode());
        assertThat(qrCodeService.findByRestaurant(restaurant.getId())).hasSize(1);
    }

    /** Voie de secours manuelle : refusée si le restaurant a déjà son QR. */
    @Test
    void createRejectsASecondQrForTheSameRestaurant() {
        Restaurant restaurant = restaurantService.create("Snack Unique", RestaurantOffer.BASIC);
        qrCodeService.create(restaurant.getId(), "QR", "https://example.com/menu.pdf");

        assertThatThrownBy(() ->
                qrCodeService.create(restaurant.getId(), "QR bis", "https://example.com/menu-bis.pdf")
        ).isInstanceOf(ConflictException.class);

        assertThat(qrCodeService.findByRestaurant(restaurant.getId())).hasSize(1);
    }

    /**
     * Dernier filet : même en contournant le service (accès direct au repository, comme
     * le ferait un futur appelant qui aurait oublié la garde de {@link QrCodeService#create}),
     * la contrainte {@code uq_qr_codes_restaurant_id} (migration V7) refuse un second QR.
     */
    @Test
    void databaseConstraintRejectsASecondQrEvenBypassingTheService() {
        Restaurant restaurant = restaurantService.create("Snack Contrainte DB", RestaurantOffer.BASIC);
        qrCodeRepository.saveAndFlush(new QrCode(restaurant.getId(), "QR 1", "https://example.com/1", "CODEUN1234"));

        assertThatThrownBy(() ->
                qrCodeRepository.saveAndFlush(
                        new QrCode(restaurant.getId(), "QR 2", "https://example.com/2", "CODEDEUX12"))
        ).isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
    }

    @Test
    void activatesAndDeactivatesQrCode() {
        Restaurant restaurant = restaurantService.create("Snack Activation", RestaurantOffer.BASIC);
        QrCode qrCode = qrCodeService.create(restaurant.getId(), "QR", "https://example.com/menu.pdf");

        QrCode deactivated = qrCodeService.deactivate(qrCode.getId());
        assertThat(deactivated.isActive()).isFalse();

        QrCode reactivated = qrCodeService.activate(qrCode.getId());
        assertThat(reactivated.isActive()).isTrue();
    }
}
